<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.example</groupId>
	<artifactId>taller-eureka-gateway</artifactId>
	<version>1.0.0</version>
	<packaging>pom</packaging>
	<name>taller-eureka-gateway</name>
	<description>Taller de Implementacion Spring Boot + Eureka Server &amp; Client + API Gateway</description>

	<modules>
		<module>EurekaServerService</module>
		<module>UserService</module>
		<module>ApiGateway</module>
	</modules>
</project>
